name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          mkdir ../website
          cp -TR . ../website
          pwd
          ls
          ls ..
      #- name: Setup Tailscale
      #  id: tailscale
      #  uses: tailscale/tailscale-deploy-github@main
      #  with:
      #    authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      #    version: 1.7.359
      - name: test ssh
        run: |
          TEMP=$(mktemp)
          echo "${{ secrets.KEY }}" > $TEMP
          USER=${{ secrets.SSH_USER }}
          HOST=${{ secrets.HOST }}
          PW=${{ secrets.password }}
          mkdir ~/.ssh
          mkdir ~/.ssh/authorized_keys/
          chmod 700 ~/.ssh
          echo "${{ secrets.pub_key }}" > ~/.ssh/authorized_keys/actions.pub
          echo "${{ secrets.key }}" > ~/.ssh/actions.pub
          echo "scp to $USER@$HOST with pass $PW"
          ssh -vv -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i $TEMP $USER@$HOST 'pwd'

      # scp -v -o StrictHostKeyChecking=no -p $PW website/* $USER@$HOST:/home/

      #- name: copy file via ssh
      #  uses:  appleboy/scp-action@master
      #  with:
      #    host: ${{ secrets.HOST }}
      #    port: 22
      #    username: ${{ secrets.SSH_USER }}
      #    #password: ${{ secrets.PASSWORD }}
      #    key: ${{ secrets.KEY }}
      #    passphrase: ${{ secrets.PASSPHRASE }}
      #    source: website/*
      #    target: "~./"