name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Deploy to sandbox via rsync
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "website/"
          target: "test"

      #- name: Run a multi-line script
      #  run: |
      #    mkdir ../website
      #    cp -TR . ../website
      #    pwd
      #    ls
      #    ls ..
      #- name: Setup Tailscale
      #  id: tailscale
      #  uses: tailscale/tailscale-deploy-github@main
      #  with:
      #    authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      #    version: 1.7.359

      #- name: copy file via ssh
      #  uses:  appleboy/scp-action@master
      #  with:
      #    host: ${{ secrets.HOST }}
      #    port: 22
      #    username: ${{ secrets.SSH_USER }}
      #    #password: ${{ secrets.PASSWORD }}
      #    key: ${{ secrets.KEY }}
      #    source: website/*
      #    target: "~./"

      #- name: Adding Known Hosts
      #  run: |
      #    mkdir ~/.ssh
      #    chmod 0700 ~/.ssh
      #    echo "${{ secrets.KEY }}" >> ~/.ssh/id_rsa
      #    chmod 0700 ~/.ssh/id_rsa
      #    ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      #- name: Deploy with rsync
      #  run: rsync -avz -i ~/.ssh/id_rsa ./website/ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/home/drose/

